apiVersion: apps/v1
kind: Deployment
metadata:
  name: project1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: project1
  template:
    metadata:
      labels:
        app: project1
    spec:
      volumes:
        - name: shared-timestamp
          persistentVolumeClaim:
            claimName: project1-claim
      containers:
        - name: timestampgen
          image: tsuribori/dwk-timestampgen:latest
          volumeMounts:
          - name: shared-timestamp
            mountPath: /usr/src/app/files
          imagePullPolicy: Always
        - name: timestampread
          image: tsuribori/dwk-timestampread:latest
          volumeMounts:
          - name: shared-timestamp
            mountPath: /usr/src/app/files
          imagePullPolicy: Always
