apiVersion: v1
kind: Service
metadata:
  name: project1-svc
  namespace: dwk-namespace
spec:
  type: ClusterIP
  selector:
    app: project1
  ports:
    - port: 2345
      protocol: TCP
      targetPort: 8080
