apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: dwk-namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: tsuribori/dwk-backend:latest
          imagePullPolicy: Always

